name: Deploy IHUB App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install SST globally
        run: npm install -g sst

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'

      - name: Build Go functions
        run: |
          # cd packages/functions
          # sudo mkdir -p .cache
          # export GOPATH="$CI_PROJECT_DIR/.cache"
          # npm ci
          # go mod download
          # go mod vendor
          # export GOPATH=$GOPATH:$(pwd)
          GOOS=linus GOARCH=amd64 go build -o packages/functions/create-person/main packages/functions/create-person/main.go
          GOOS=linus GOARCH=amd64 go build -o packages/functions/list-person/main packages/functions/list-person/main.go


      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to AWS
        run: npx sst deploy
